# Name of the workflow
name: Generate Snake Animation

# Controls when the action will run
on:
  # This runs the job every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # This will also run the workflow on a push to the master branch
  push:
    branches:
      - master

jobs:
  # A single job called "generate"
  generate:
    # Required permissions for the crazy-max/ghaction-github-pages action
    permissions:
      contents: write

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # A time limit for the job
    timeout-minutes: 5

    # A sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Generate the snake.svg file
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}

          # The output file for the animation, with a dark theme
          outputs: dist/snake.svg?palette=github-dark

      # Step 2: Push the generated file to the "output" branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # The branch to push the generated files to
          target_branch: output
          # The directory where the generated files are
          build_dir: dist
        env:
          # A token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
